version: "3"

services:
  backend:
    image: betterfactory-backend
    build:
      context: .
    network_mode: "host"
    devices:
      - "/dev:/dev:ro"
    privileged: true
    command: python3 wpc.py -m models/FP16/human-pose-estimation-3d-0001.xml -use_rs true -o_url http://localhost:1026
    # command: sleep infinity
    environment:
      - PYTHONUNBUFFERED=1 # keep pythons output running
      - "DISPLAY" # activate graphical environment
      - "QT_X11_NO_MITSHM=1" # fix some QT bugs
    user: "1000:44" # claim being you (1000) in order to access your x11 and of group video (44) to access camera
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # share your x11 socket
      - .:/app
